// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWrAoFm91L-cG6x1K5mK5ypj39P6PqWY',
    appId: '1:831606316240:web:7665c4f0bc721bcd9bd2d5',
    messagingSenderId: '831606316240',
    projectId: 'peacedev-test',
    authDomain: 'peacedev-test.firebaseapp.com',
    storageBucket: 'peacedev-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa1tIv9P7qKEZoB_-g4F0TdllQVJQz8Js',
    appId: '1:831606316240:android:8ab79c71c5ebffb89bd2d5',
    messagingSenderId: '831606316240',
    projectId: 'peacedev-test',
    storageBucket: 'peacedev-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIcFX1QgrG_v0tb708Kop1Z0OikVs2RDk',
    appId: '1:831606316240:ios:8448b5922f2ab8599bd2d5',
    messagingSenderId: '831606316240',
    projectId: 'peacedev-test',
    storageBucket: 'peacedev-test.appspot.com',
    iosClientId: '831606316240-u8bdstrsqm92li3gdquv637ktgsc833m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPeacedev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIcFX1QgrG_v0tb708Kop1Z0OikVs2RDk',
    appId: '1:831606316240:ios:8448b5922f2ab8599bd2d5',
    messagingSenderId: '831606316240',
    projectId: 'peacedev-test',
    storageBucket: 'peacedev-test.appspot.com',
    iosClientId: '831606316240-u8bdstrsqm92li3gdquv637ktgsc833m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPeacedev',
  );
}
